# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Shara API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_HOST: 127.0.0.1
          envkey_PORT: 3333
          envkey_NODE_ENV: development
          envkey_APP_NAME: Shara
          envkey_APP_URL: http://${HOST}:${PORT}
          envkey_CACHE_VIEWS:
          envkey_APP_KEY:
          envkey_DB_CONNECTION: pg
          envkey_DB_HOST: 127.0.0.1
          envkey_DB_PORT: 5432
          envkey_DB_USER: postgres
          envkey_DB_PASSWORD: postgres
          envkey_DB_DATABASE: shara
          envkey_HASH_DRIVER: bcrypt
          file_name: .env
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
